const { GoogleGenerativeAI } = require('@google/generative-ai');
const logger = require('../config/logger');

// Initialize Gemini client
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Model configuration based on available Gemini models
const MODELS = {
  TEXT: 'gemini-2.5-flash',                                    // For text analysis
  AUDIO_TRANSCRIPTION: 'gemini-2.5-flash',                     // For audio transcription
  TTS: 'gemini-2.5-flash',                         // For text-to-speech
  NATIVE_AUDIO: 'gemini-2.5-flash-native-audio-preview-12-2025'         // For bidirectional audio
};

/**
 * Transcribe audio using Gemini with structured output
 * @param {Buffer} audioBuffer - Audio data buffer
 * @param {string} mimeType - Audio MIME type (audio/wav, audio/mp3, audio/webm, etc.)
 * @returns {Promise<Object>} Transcription result with language detection and emotion
 */
async function transcribeAudio(audioBuffer, mimeType = 'audio/wav') {
  try {
    const model = genAI.getGenerativeModel({ 
      model: MODELS.AUDIO_TRANSCRIPTION,
      generationConfig: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'object',
          properties: {
            transcript: {
              type: 'string',
              description: 'Exact words spoken by the patient'
            },
            language: {
              type: 'string',
              description: 'Detected language name (English, Hindi, Bengali, Tamil, etc.)'
            },
            language_code: {
              type: 'string',
              description: 'ISO language code (en, hi, bn, ta, etc.)'
            },
            translation: {
              type: 'string',
              description: 'English translation if not in English'
            },
            emotion: {
              type: 'string',
              enum: ['happy', 'sad', 'anxious', 'neutral', 'distressed', 'calm', 'angry', 'worried'],
              description: 'Detected speaker emotion'
            },
            urgency: {
              type: 'string',
              enum: ['low', 'medium', 'high', 'critical'],
              description: 'Assessed urgency level based on symptoms'
            },
            symptoms: {
              type: 'array',
              items: { type: 'string' },
              description: 'List of medical symptoms mentioned'
            },
            confidence: {
              type: 'number',
              description: 'Confidence score between 0 and 1'
            }
          },
          required: ['transcript', 'language', 'language_code', 'emotion', 'urgency', 'symptoms', 'confidence']
        }
      }
    });
    
    const prompt = `
      Process this audio file and generate a detailed transcription with medical analysis.
      
      Requirements:
      1. Provide accurate transcription of what the patient said
      2. Detect the primary language (English, Hindi, Bengali, Tamil, Telugu, Marathi, etc.)
      3. If not in English, provide English translation
      4. Detect speaker emotion (choose one: happy, sad, anxious, neutral, distressed, calm, angry, worried)
      5. Assess urgency level based on symptoms (low, medium, high, critical)
      6. Extract all medical symptoms mentioned
      7. Provide confidence score for the transcription
    `;
    
    const result = await model.generateContent([
      {
        inlineData: {
          data: audioBuffer.toString('base64'),
          mimeType: mimeType
        }
      },
      prompt
    ]);
    
    const response = await result.response;
    const text = response.text();
    
    // Parse JSON response
    const parsed = JSON.parse(text);
    
    logger.info('Audio transcribed successfully', { 
      model: MODELS.AUDIO_TRANSCRIPTION,
      language: parsed.language, 
      emotion: parsed.emotion,
      urgency: parsed.urgency,
      symptoms_count: parsed.symptoms?.length || 0
    });
    
    return parsed;
    
  } catch (error) {
    logger.error('Audio transcription failed:', error);
    throw new Error('Failed to transcribe audio: ' + error.message);
  }
}

/**
 * Transcribe the audio response generated by the AI so it can be displayed as text.
 */
async function transcribeResponseAudio(audioBuffer, mimeType = 'audio/pcm;rate=24000') {
  try {
    const model = genAI.getGenerativeModel({ 
      model: MODELS.AUDIO_TRANSCRIPTION,
      generationConfig: {
        responseMimeType: 'text/plain',
      }
    });
    
    const prompt = `Please provide an exact, word-for-word transcript of the spoken audio in this file. Return only the transcript text.`;
    
    const result = await model.generateContent([
      {
        inlineData: {
          data: audioBuffer.toString('base64'),
          mimeType: mimeType
        }
      },
      prompt
    ]);
    
    const response = await result.response;
    return response.text().trim();
  } catch (error) {
    logger.error('Response audio transcription failed:', error);
    return null;
  }
}

/**
 * Conduct AI triage conversation using Gemini (via OpenAI compatibility layer for better language control)
 * @param {string} transcript - Patient's spoken symptoms
 * @param {Object} patientHistory - Patient's medical history
 * @param {Array} conversationHistory - Previous conversation
 * @param {string} language - Language code (en, hi, etc.)
 * @returns {Promise<Object>} AI response with questions and analysis
 */
async function conductTriageConversation(transcript, patientHistory = {}, conversationHistory = [], language = 'en') {
  try {
    const { callGemini } = require('../config/gemini');
    
    const conversationCount = conversationHistory.length;
    const maxQuestions = 5; // Increased from 2 to 5 for better assessment
    
    const isEnglish = language === 'en';
    
    const systemMessage = isEnglish
      ? `You are a medical triage AI assistant. You MUST respond ONLY in English language.
         CRITICAL: Do NOT use Hindi, Spanish, Bengali, Tamil, Telugu, Marathi, or ANY other language.
         Every single word in your response must be in English.`
      : `You are a medical triage AI assistant. You MUST respond in ${language === 'hi' ? 'Hindi (हिंदी)' : language} language only.`;
    
    const userMessage = `
MEDICAL TRIAGE ASSESSMENT

Patient Statement: "${transcript}"
Patient History: ${JSON.stringify(patientHistory)}
Previous Conversation: ${conversationHistory.map(h => `${h.role}: ${h.content}`).join('\n')}

Conversation Progress: ${conversationCount}/${maxQuestions} questions asked
${conversationCount >= maxQuestions ? '⚠️ FINAL ASSESSMENT - Set needs_more_info to false' : ''}

INSTRUCTIONS:
1. ${conversationCount >= maxQuestions ? 'Provide a brief, reassuring closing statement summarizing the assessment. DO NOT ASK ANY MORE QUESTIONS.' : 'Ask ONE focused follow-up question'}
2. Assess urgency (0-100): <40=Routine, 40-69=OPD, 70+=Emergency
3. Identify symptoms
4. Recommend specialty
5. Provide immediate precautions
6. Provide specific, actionable immediate advice in 'empathy_response' (not just "I understand")

${isEnglish ? 'RESPOND IN ENGLISH ONLY. DO NOT USE ANY OTHER LANGUAGE.' : `RESPOND IN ${language.toUpperCase()} ONLY.`}

Return ONLY valid JSON with this exact structure. DO NOT USE trailing commas or comments. The keys must be exact:
{
  "question": "${conversationCount >= maxQuestions ? 'Assessment complete. Please review the advice below.' : 'Your question'}",
  "question_english": "English version for logging",
  "urgency_score": 50,
  "reasoning": "Your reasoning",
  "symptoms_identified": ["symptom1", "symptom2"],
  "recommended_specialty": "Specialty name",
  "recommended_action": "OPD",
  "needs_more_info": ${conversationCount >= maxQuestions ? 'false' : 'true'},
  "empathy_response": "Empathetic response",
  "immediate_precautions": ["precaution1", "precaution2"]
}`;

    const messages = [
      { role: 'system', content: systemMessage },
      { role: 'user', content: userMessage }
    ];
    
    const response = await callGemini(messages, { 
      temperature: 0.7,
      max_tokens: 1000,
      response_format: { type: "json_object" }
    });
    
    if (!response.success) {
      throw new Error(response.error);
    }
    
    // Extract JSON from response
    let jsonText = response.content.trim();
    
    // Remove markdown code blocks if present
    if (jsonText.startsWith('```json')) {
      jsonText = jsonText.replace(/```json\n?/g, '').replace(/```\n?/g, '');
    } else if (jsonText.startsWith('```')) {
      jsonText = jsonText.replace(/```\n?/g, '');
    }
    
    let parsed;
    try {
      // In case it's incomplete due to token limit
      if (!jsonText.endsWith('}')) {
          jsonText = jsonText + '"}'; // close what we can
      }
      parsed = JSON.parse(jsonText);
    } catch (parseError) {
      logger.error('JSON parse error from Gemini triage response. Raw text:', jsonText);
      // Fallback response if parsing fails
      parsed = {
        question: conversationCount >= maxQuestions ? "Assessment complete. Please proceed to booking." : "Could you elaborate more on how you're feeling?",
        question_english: conversationCount >= maxQuestions ? "Assessment complete. Please proceed to booking." : "Could you elaborate more on how you're feeling?",
        urgency_score: 50,
        reasoning: "Failed to parse AI response, continuing with fallback.",
        symptoms_identified: [],
        recommended_specialty: "General Physician",
        recommended_action: "OPD",
        needs_more_info: conversationCount < maxQuestions,
        empathy_response: "Please consult a doctor for a proper evaluation. Rest and monitor your symptoms.",
        immediate_precautions: ["Rest and monitor your symptoms."]
      };
    }
    
    // Force needs_more_info to false after max questions
    if (conversationCount >= maxQuestions) {
      parsed.needs_more_info = false;
      // Ensure the question field doesn't look like a question if we are done
      if (parsed.question && (parsed.question.includes('?') || parsed.question.length < 5)) {
        parsed.question = "Thank you. I have analyzed your symptoms. Please review the assessment below.";
      }
    }
    
    logger.info('Triage conversation completed', { 
      urgency_score: parsed.urgency_score,
      specialty: parsed.recommended_specialty,
      conversation_count: conversationCount,
      needs_more_info: parsed.needs_more_info,
      language: language
    });
    
    return parsed;
    
  } catch (error) {
    logger.error('Triage conversation failed:', error);
    throw new Error('Failed to conduct triage: ' + error.message);
  }
}

/**
 * Generate voice response using Gemini TTS
 * @param {string} text - Text to convert to speech
 * @param {string} language - Language code (en, hi)
 * @param {string} voiceName - Voice name (Puck, Charon, Kore, Fenrir, Aoede)
 * @returns {Promise<Object>} Audio buffer and metadata
 */
async function generateVoiceResponse(text, language = 'en', voiceName = 'Aoede') {
  try {
    const model = genAI.getGenerativeModel({ 
      model: MODELS.TTS
    });
    
    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text }] }],
      generationConfig: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: voiceName
            }
          }
        }
      }
    });
    
    const response = await result.response;
    
    // Check if audio is available
    if (response.candidates && response.candidates[0]?.content?.parts?.[0]?.inlineData) {
      const audioData = response.candidates[0].content.parts[0].inlineData.data;
      
      logger.info('Voice response generated with audio', { 
        model: MODELS.TTS,
        text_length: text.length,
        voice: voiceName,
        language 
      });
      
      return {
        audio: Buffer.from(audioData, 'base64'),
        mimeType: 'audio/pcm',
        text: text,
        audio_available: true
      };
    } else {
      // Fallback to text
      logger.warn('Audio not available in response, returning text');
      return {
        text: text,
        audio_available: false,
        message: 'Audio generation not available, returning text'
      };
    }
    
  } catch (error) {
    logger.error('Voice generation failed:', error);
    // Fallback to text-only response
    return {
      text: text,
      audio_available: false,
      message: 'TTS temporarily unavailable: ' + error.message
    };
  }
}

/**
 * Analyze symptoms and provide medical insights
 * @param {Array} symptoms - List of symptoms
 * @param {Object} patientHistory - Patient's medical history
 * @returns {Promise<Object>} Medical analysis
 */
async function analyzeSymptoms(symptoms, patientHistory = {}) {
  try {
    const model = genAI.getGenerativeModel({ 
      model: MODELS.TEXT,
      generationConfig: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'object',
          properties: {
            urgency_score: {
              type: 'number',
              description: 'Urgency score from 0-100'
            },
            likely_conditions: {
              type: 'array',
              items: { type: 'string' },
              description: 'List of possible conditions'
            },
            red_flags: {
              type: 'array',
              items: { type: 'string' },
              description: 'Serious symptoms needing immediate attention'
            },
            recommended_specialty: {
              type: 'string',
              description: 'Recommended medical specialty'
            },
            recommended_action: {
              type: 'string',
              enum: ['ED', 'OPD', 'Routine', 'Teleconsult'],
              description: 'Recommended action'
            },
            reasoning: {
              type: 'string',
              description: 'Explanation of assessment'
            },
            questions_to_ask: {
              type: 'array',
              items: { type: 'string' },
              description: 'Additional questions needed'
            },
            immediate_advice: {
              type: 'string',
              description: 'What patient should do now'
            }
          },
          required: ['urgency_score', 'likely_conditions', 'red_flags', 'recommended_specialty', 'recommended_action', 'reasoning', 'questions_to_ask', 'immediate_advice']
        }
      }
    });
    
    const prompt = `
      As a medical AI assistant, analyze these symptoms and patient history:
      
      Symptoms: ${JSON.stringify(symptoms)}
      Patient History: ${JSON.stringify(patientHistory)}
      
      Provide comprehensive medical analysis following the schema.
    `;
    
    const result = await model.generateContent([prompt]);
    const response = await result.response;
    const text = response.text();
    
    const parsed = JSON.parse(text);
    
    logger.info('Symptoms analyzed', { 
      model: MODELS.TEXT,
      urgency: parsed.urgency_score,
      conditions: parsed.likely_conditions?.length || 0 
    });
    
    return parsed;
    
  } catch (error) {
    logger.error('Symptom analysis failed:', error);
    throw new Error('Failed to analyze symptoms: ' + error.message);
  }
}

module.exports = {
  transcribeAudio,
  transcribeResponseAudio,
  conductTriageConversation,
  generateVoiceResponse,
  analyzeSymptoms,
  MODELS
};