apiVersion: v1
kind: ConfigMap
metadata:
  name: medhaos-config
  labels:
    app.kubernetes.io/name: medhaos
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
