/**
 * Sample Recovery Plan Data
 * Mock data for development and testing
 */

import { RecoveryPlan } from '@store/recoveryStore';

export const sampleRecoveryPlan: RecoveryPlan = {
  id: 'recovery-001',
  patientId: 'patient-001',
  condition: 'Post-Cardiac Surgery (CABG)',
  dischargeDate: '2026-02-20T10:00:00Z',
  overallProgress: 45,
  phases: [
    {
      id: 'phase-1',
      name: 'Immediate Recovery (Week 1-2)',
      description: 'Focus on rest, wound care, and gradual mobility',
      startDate: '2026-02-20T00:00:00Z',
      endDate: '2026-03-06T00:00:00Z',
      status: 'completed',
      progress: 100,
      milestones: [
        {
          id: 'milestone-1-1',
          title: 'First Follow-up Visit',
          description: 'Check wound healing and vital signs',
          dueDate: '2026-02-27T10:00:00Z',
          completed: true,
          completedDate: '2026-02-27T10:30:00Z',
        },
        {
          id: 'milestone-1-2',
          title: 'Remove Surgical Staples',
          description: 'Surgical staples removal at clinic',
          dueDate: '2026-03-05T14:00:00Z',
          completed: true,
          completedDate: '2026-03-05T14:15:00Z',
        },
      ],
      activities: [
        {
          id: 'activity-1-1',
          type: 'medication',
          title: 'Take prescribed medications',
          description: 'Blood thinners, pain management, antibiotics',
          frequency: '3 times daily',
          completed: true,
          icon: '💊',
        },
        {
          id: 'activity-1-2',
          type: 'restriction',
          title: 'Avoid heavy lifting',
          description: 'No lifting objects over 5kg',
          frequency: 'Continuous',
          completed: true,
          icon: '⚠️',
        },
        {
          id: 'activity-1-3',
          type: 'checkup',
          title: 'Monitor wound site',
          description: 'Check for signs of infection daily',
          frequency: 'Daily',
          completed: true,
          icon: '🩹',
        },
      ],
    },
    {
      id: 'phase-2',
      name: 'Early Recovery (Week 3-6)',
      description: 'Gradual increase in activity and cardiac rehabilitation',
      startDate: '2026-03-07T00:00:00Z',
      endDate: '2026-04-04T00:00:00Z',
      status: 'active',
      progress: 60,
      milestones: [
        {
          id: 'milestone-2-1',
          title: 'Start Cardiac Rehab Program',
          description: 'Begin supervised exercise program',
          dueDate: '2026-03-10T09:00:00Z',
          completed: true,
          completedDate: '2026-03-10T09:30:00Z',
        },
        {
          id: 'milestone-2-2',
          title: 'Echocardiogram Test',
          description: 'Assess heart function post-surgery',
          dueDate: '2026-03-20T11:00:00Z',
          completed: false,
        },
        {
          id: 'milestone-2-3',
          title: 'Cardiologist Follow-up',
          description: 'Review recovery progress and test results',
          dueDate: '2026-03-28T15:00:00Z',
          completed: false,
        },
      ],
      activities: [
        {
          id: 'activity-2-1',
          type: 'exercise',
          title: 'Walking Exercise',
          description: 'Walk 15-20 minutes, 2 times daily',
          frequency: 'Twice daily',
          completed: false,
          icon: '🚶',
        },
        {
          id: 'activity-2-2',
          type: 'diet',
          title: 'Heart-Healthy Diet',
          description: 'Low sodium, high fiber, lean proteins',
          frequency: 'All meals',
          completed: false,
          icon: '🥗',
        },
        {
          id: 'activity-2-3',
          type: 'medication',
          title: 'Continue Medications',
          description: 'Aspirin, statins, beta-blockers as prescribed',
          frequency: 'Daily',
          completed: false,
          icon: '💊',
        },
        {
          id: 'activity-2-4',
          type: 'checkup',
          title: 'Monitor Blood Pressure',
          description: 'Check BP twice daily, record readings',
          frequency: 'Twice daily',
          completed: false,
          icon: '🩺',
        },
      ],
    },
    {
      id: 'phase-3',
      name: 'Intermediate Recovery (Week 7-12)',
      description: 'Increase activity levels and return to light work',
      startDate: '2026-04-05T00:00:00Z',
      endDate: '2026-05-10T00:00:00Z',
      status: 'upcoming',
      progress: 0,
      milestones: [
        {
          id: 'milestone-3-1',
          title: 'Stress Test',
          description: 'Exercise stress test to assess heart capacity',
          dueDate: '2026-04-15T10:00:00Z',
          completed: false,
        },
        {
          id: 'milestone-3-2',
          title: 'Return to Work Assessment',
          description: 'Evaluate readiness for work activities',
          dueDate: '2026-04-25T14:00:00Z',
          completed: false,
        },
      ],
      activities: [
        {
          id: 'activity-3-1',
          type: 'exercise',
          title: 'Increased Walking',
          description: 'Walk 30-40 minutes daily',
          frequency: 'Daily',
          completed: false,
          icon: '🚶',
        },
        {
          id: 'activity-3-2',
          type: 'exercise',
          title: 'Light Strength Training',
          description: 'Upper body exercises with light weights',
          frequency: '3 times weekly',
          completed: false,
          icon: '💪',
        },
      ],
    },
    {
      id: 'phase-4',
      name: 'Long-term Recovery (Month 4-6)',
      description: 'Return to normal activities with lifestyle modifications',
      startDate: '2026-05-11T00:00:00Z',
      endDate: '2026-08-11T00:00:00Z',
      status: 'upcoming',
      progress: 0,
      milestones: [
        {
          id: 'milestone-4-1',
          title: 'Final Cardiologist Review',
          description: 'Comprehensive assessment of recovery',
          dueDate: '2026-06-15T11:00:00Z',
          completed: false,
        },
      ],
      activities: [
        {
          id: 'activity-4-1',
          type: 'exercise',
          title: 'Regular Exercise Routine',
          description: 'Maintain 150 minutes of moderate activity weekly',
          frequency: 'Weekly',
          completed: false,
          icon: '🏃',
        },
        {
          id: 'activity-4-2',
          type: 'diet',
          title: 'Maintain Healthy Diet',
          description: 'Continue heart-healthy eating habits',
          frequency: 'Ongoing',
          completed: false,
          icon: '🥗',
        },
      ],
    },
  ],
  educationalContent: [
    {
      id: 'content-1',
      title: 'हृदय रोग के बाद आहार',
      description: 'Heart-healthy diet after cardiac surgery',
      type: 'video',
      category: 'diet',
      language: 'hi',
      duration: 330,
      thumbnailUrl: 'https://example.com/thumbnails/diet-hindi.jpg',
      contentUrl: 'https://example.com/videos/diet-hindi.mp4',
      watched: true,
      watchProgress: 100,
      tags: ['diet', 'nutrition', 'heart-health'],
    },
    {
      id: 'content-2',
      title: 'Cardiac Rehabilitation Exercises',
      description: 'Safe exercises for post-surgery recovery',
      type: 'video',
      category: 'exercise',
      language: 'en',
      duration: 480,
      thumbnailUrl: 'https://example.com/thumbnails/exercise-en.jpg',
      contentUrl: 'https://example.com/videos/exercise-en.mp4',
      watched: false,
      watchProgress: 45,
      tags: ['exercise', 'rehabilitation', 'recovery'],
    },
    {
      id: 'content-3',
      title: 'Understanding Your Medications',
      description: 'Guide to post-surgery medications',
      type: 'video',
      category: 'medication',
      language: 'en',
      duration: 420,
      thumbnailUrl: 'https://example.com/thumbnails/meds-en.jpg',
      contentUrl: 'https://example.com/videos/meds-en.mp4',
      watched: false,
      watchProgress: 0,
      tags: ['medication', 'education'],
    },
    {
      id: 'content-4',
      title: 'Wound Care After Surgery',
      description: 'How to care for your surgical wound',
      type: 'video',
      category: 'wound-care',
      language: 'en',
      duration: 300,
      thumbnailUrl: 'https://example.com/thumbnails/wound-en.jpg',
      contentUrl: 'https://example.com/videos/wound-en.mp4',
      watched: true,
      watchProgress: 100,
      tags: ['wound-care', 'recovery'],
    },
    {
      id: 'content-5',
      title: 'तनाव प्रबंधन तकनीक',
      description: 'Stress management techniques for recovery',
      type: 'video',
      category: 'mental-health',
      language: 'hi',
      duration: 360,
      thumbnailUrl: 'https://example.com/thumbnails/stress-hindi.jpg',
      contentUrl: 'https://example.com/videos/stress-hindi.mp4',
      watched: false,
      watchProgress: 0,
      tags: ['mental-health', 'stress', 'wellness'],
    },
  ],
  followUpAppointments: [
    {
      id: 'appt-1',
      date: '2026-03-20',
      time: '11:00 AM',
      doctor: 'Dr. Anjali Verma',
      specialty: 'Cardiology',
      purpose: 'Echocardiogram and progress review',
      status: 'scheduled',
    },
    {
      id: 'appt-2',
      date: '2026-03-28',
      time: '3:00 PM',
      doctor: 'Dr. Anjali Verma',
      specialty: 'Cardiology',
      purpose: 'Review test results and adjust medications',
      status: 'scheduled',
    },
  ],
  emergencyContacts: [
    {
      id: 'contact-1',
      name: 'Dr. Anjali Verma',
      role: 'Cardiologist',
      phone: '+91-98765-43210',
      available24x7: false,
    },
    {
      id: 'contact-2',
      name: 'Apollo Hospital Emergency',
      role: 'Emergency Department',
      phone: '+91-11-2345-6789',
      available24x7: true,
    },
    {
      id: 'contact-3',
      name: 'Cardiac Rehab Coordinator',
      role: 'Rehabilitation Support',
      phone: '+91-98765-11111',
      available24x7: false,
    },
  ],
};
